version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build:
      context: ./frontend/user-management-fronted
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    restart: always