---
apiVersion: v1
kind: Service
metadata:
  name: frontend-userflow
  labels:
    app: frontend-userflow
spec:
  selector:
    app: frontend-userflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---