apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-userflow
spec:
  selector:
    matchLabels:
      app: frontend-userflow
  template:
    metadata:
      labels:
        app: frontend-userflow
    spec:
      containers:
      - name: frontend-userflow
        image: userflow-frontend:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80