version: '3.8'

services:
  frontend-client-panel:
    container_name: frontend-client-panel
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
  backend-user-service:
    container_name: backend-user-service
    build:
      context: ./backend/create-user-service/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"