version: '3.8'

services:
  frontend-dashboard-service:
    container_name: frontend-dashboard-service
    build:
      context: ./dashboard-service/frontend/user-management-frontend
      dockerfile: Dockerfile
  
  frontend-login-service:
    container_name: frontend-login-service
    build:
      context: ./login-services/frontend/
      dockerfile: Dockerfile

  frontend-user-service:
    container_name: frontend-user-service
    build:
      context: ./create-user-service/frontend/
      dockerfile: Dockerfile
  backend-dashboard-service:
    container_name: backend-dashboard-service
    build:
      context: ./dashboard-service/backend
      dockerfile: Dockerfile
  backend-user-service:
    container_name: backend-user-service
    build:
      context: ./create-user-service/backend/
      dockerfile: Dockerfile
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"