name: Test Userflow docker images

on:
  push:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the backend Dockerfile
      run: cd local/backend/ && docker build --tag my-backend:$(date +%s) .

    - name: Build the frontend Dockerfile
      run: cd local/frontend/user-management-fronted && docker build --tag my-frontend:$(date +%s) .

    - name: Show the Docker images
      run: docker images