name: Test Userflow docker images

on:
  push:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the backend Dockerfile
      run: cd local/backend/ && docker build --tag my-backend:$(date +%s) .
