name: Test the changes in my client-panel app

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - 'app/client-panel'
      - 'dev'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the backend Dockerfile
      run: cd client-panel/local/backend/ && docker build --tag my-backend:$(date +%s) .

    - name: Build the frontend Dockerfile
      run: cd client-panel/local/frontend/user-management-fronted && docker build --tag my-frontend:$(date +%s) .

    - name: Show the Docker images
      run: docker images
